name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend deps
        working-directory: backend
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        working-directory: backend
        run: |
          . .venv/bin/activate
          python -m pytest -q

  docker-build:
    runs-on: ubuntu-latest
    needs: backend-tests
    steps:
      - uses: actions/checkout@v4
      - name: Build backend image
        run: docker build -t business-monitor-backend -f backend/Dockerfile .
      - name: Build frontend image
        run: docker build -t business-monitor-frontend -f frontend/Dockerfile .